[package]
name = "flashyi/boilerplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
refx = "wad4444/refx@0.3.0"

maid = "flamenco687/maid@3.2.2"

observer = "tazmondo/observer@0.3.4"
packet = "sjdinsd/packet@0.1.91"

camerashaker = "brittonfischer/camerashaker@0.1.0"

conch = "alicesaidhi/conch@0.3.0-rc.6"
conch_ui = "alicesaidhi/conch-ui@0.3.0-rc.6"

dataservice = "leifstout/dataservice@0.3.0"

Signal = "sleitnick/signal@2.0.3"
replica = "ayrezrblx/replica@0.1.9"
hitbox = "flashyiii/hitbox@0.0.5"
charm = "neohertz/charm@0.11.0"
ripple = "littensy/ripple@0.9.3"
debug = "howmanysmall/debug@1.0.1"


[server-dependencies]
